services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\SchemaBib\:
    resource: '../Classes/*'

  Brotkrueml\SchemaBib\EventListener\RegisterAdditionalProperties:
    tags:
      - name: event.listener
        identifier: 'ext-schema-bib/registerAdditionalProperties'

  Brotkrueml\SchemaBib\EventListener\RegisterTypePropertiesMovedFromOfficialToPending:
    tags:
      - name: event.listener
        identifier: 'ext-schema-bib/registerTypePropertiesMovedFromOfficialToPending'
